// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'stat_snapshot.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$StatSnapshotImpl _$$StatSnapshotImplFromJson(Map<String, dynamic> json) =>
    _$StatSnapshotImpl(
      rushingAttempts: (json['23'] as num?)?.toDouble(),
      rushingYards: (json['24'] as num?)?.toDouble(),
      rushingTouchdowns: (json['25'] as num?)?.toDouble(),
      rushing2PtConversions: (json['26'] as num?)?.toDouble(),
      var5: (json['27'] as num?)?.toDouble(),
      var6: (json['28'] as num?)?.toDouble(),
      var7: (json['29'] as num?)?.toDouble(),
      var8: (json['30'] as num?)?.toDouble(),
      var9: (json['31'] as num?)?.toDouble(),
      var10: (json['33'] as num?)?.toDouble(),
      var11: (json['34'] as num?)?.toDouble(),
      var12: (json['35'] as num?)?.toDouble(),
      var13: (json['36'] as num?)?.toDouble(),
      var14: (json['37'] as num?)?.toDouble(),
      var15: (json['38'] as num?)?.toDouble(),
      averageYardsPerRushAttempt: (json['39'] as num?)?.toDouble(),
      var17: (json['40'] as num?)?.toDouble(),
      receivingYards: (json['42'] as num?)?.toDouble(),
      receivingTouchdowns: (json['43'] as num?)?.toDouble(),
      receiving2PtConversions: (json['44'] as num?)?.toDouble(),
      var21: (json['45'] as num?)?.toDouble(),
      var22: (json['46'] as num?)?.toDouble(),
      var23: (json['47'] as num?)?.toDouble(),
      var24: (json['48'] as num?)?.toDouble(),
      var25: (json['49'] as num?)?.toDouble(),
      var26: (json['50'] as num?)?.toDouble(),
      receivingReceptions: (json['53'] as num?)?.toDouble(),
      var28: (json['56'] as num?)?.toDouble(),
      var29: (json['57'] as num?)?.toDouble(),
      var30: (json['58'] as num?)?.toDouble(),
      averageYardsPerReception: (json['60'] as num?)?.toDouble(),
      receivingLongReceptions: (json['61'] as num?)?.toDouble(),
      var33: (json['62'] as num?)?.toDouble(),
      var34: (json['63'] as num?)?.toDouble(),
      var35: (json['66'] as num?)?.toDouble(),
      var36: (json['67'] as num?)?.toDouble(),
      var37: (json['68'] as num?)?.toDouble(),
      var38: (json['70'] as num?)?.toDouble(),
      var39: (json['71'] as num?)?.toDouble(),
      rusingFumbles: (json['72'] as num?)?.toDouble(),
      rushingFumblesLost: (json['73'] as num?)?.toDouble(),
      var42: (json['210'] as num?)?.toDouble(),
      var43: (json['212'] as num?)?.toDouble(),
      receivingFirstDowns: (json['213'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$$StatSnapshotImplToJson(_$StatSnapshotImpl instance) =>
    <String, dynamic>{
      '23': instance.rushingAttempts,
      '24': instance.rushingYards,
      '25': instance.rushingTouchdowns,
      '26': instance.rushing2PtConversions,
      '27': instance.var5,
      '28': instance.var6,
      '29': instance.var7,
      '30': instance.var8,
      '31': instance.var9,
      '33': instance.var10,
      '34': instance.var11,
      '35': instance.var12,
      '36': instance.var13,
      '37': instance.var14,
      '38': instance.var15,
      '39': instance.averageYardsPerRushAttempt,
      '40': instance.var17,
      '42': instance.receivingYards,
      '43': instance.receivingTouchdowns,
      '44': instance.receiving2PtConversions,
      '45': instance.var21,
      '46': instance.var22,
      '47': instance.var23,
      '48': instance.var24,
      '49': instance.var25,
      '50': instance.var26,
      '53': instance.receivingReceptions,
      '56': instance.var28,
      '57': instance.var29,
      '58': instance.var30,
      '60': instance.averageYardsPerReception,
      '61': instance.receivingLongReceptions,
      '62': instance.var33,
      '63': instance.var34,
      '66': instance.var35,
      '67': instance.var36,
      '68': instance.var37,
      '70': instance.var38,
      '71': instance.var39,
      '72': instance.rusingFumbles,
      '73': instance.rushingFumblesLost,
      '210': instance.var42,
      '212': instance.var43,
      '213': instance.receivingFirstDowns,
    };
